server:
  port: 8100

spring:
  application:
    name: consumer

eureka:
  instance:
    prefer-ip-address: true # 注册服务的时候使用服务的ip地址
    status-page-url-path: /swagger-ui.html # 服务指向/swagger-ui.html
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/  # 提供给其他服务的eureka注册地址
